#!/usr/bin/env python3
#https://github.com/mor16fsu/bch5884
#Mitchell Roth

from DNALib import *  
import fastaparser
from matplotlib import pyplot as plt

print("")

print("The DNA input sequence is:")

#Parse FASTA file 

with open("mEGFP2.fa") as fasta_file:
    parser=fastaparser.Reader(fasta_file,parse_method='quick')
    for seq in parser:
        print(seq.sequence)
        print()

print("")
print("If error in sequence print False, if no errors print None")
print(checkseq(seq.sequence))

print("")
print("The frequency of each nucleotide is:")
print(countnuc(seq.sequence))

print("")
print("The transcript of the sequence is:")
print(transcribe(seq.sequence))

print("")
print("The reverse complement is:")
print(reverse_complement(seq.sequence))

print("")
print("The protein sequence is:")
print(translate(seq.sequence,aminodict))

print("")
print("The GC content % is:")
print(GC(seq.sequence))

print("")
print("The Human codon optimized sequence is:")
print(human_optimize(seq.sequence,humandict))


print("")
print("The Tm of the DNA sequence in degrees C is:")
print(tm(seq.sequence))

print("")

#Graph 
print(plot(seq.sequence))

###HTML###

def writeHTML():
    f=open("mitchellfinalproject.html",'w')
    f.write("<DOCTYPE html>")
    f.write("<html>\n")
    f.write("<head>\n")
    f.write("<h1> DNA Analysis of mEGFP gene from FASTA file mEGFP2 </p>\n")
    f.write("<style> body { background:gold; }\n") 
    f.write("</style>\n")
    f.write("</head>\n")
    f.write("<body>\n")
    f.write("<h2> By using this program, I am able to analyze DNA sequence data from FASTA files.\n I can utilize this program to analyze FASTA files of genes and for primer data.</h2>\n")
    f.write("<br>\n")
    f.write("<p> The DNA input sequence is: ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA</p>\n")
    f.write("<br>\n")
    f.write("<p> The frequency of each nucleotide is:{'A': 174, 'C': 240, 'G': 203, 'T': 103} </p>\n")
    f.write("<br>\n")
    f.write("<img src='Figure_1.png' width='650' height='450'/>\n")
    f.write("<br>\n") 
    f.write("<p> The transcript of the sequence is: AUGGUGAGCAAGGGCGAGGAGCUGUUCACCGGGGUGGUGCCCAUCCUGGUCGAGCUGGACGGCGACGUAAACGGCCACAAGUUCAGCGUGUCCGGCGAGGGCGAGGGCGAUGCCACCUACGGCAAGCUGACCCUGAAGUUCAUCUGCACCACCGGCAAGCUGCCCGUGCCCUGGCCCACCCUCGUGACCACCCUGACCUACGGCGUGCAGUGCUUCAGCCGCUACCCCGACCACAUGAAGCAGCACGACUUCUUCAAGUCCGCCAUGCCCGAAGGCUACGUCCAGGAGCGCACCAUCUUCUUCAAGGACGACGGCAACUACAAGACCCGCGCCGAGGUGAAGUUCGAGGGCGACACCCUGGUGAACCGCAUCGAGCUGAAGGGCAUCGACUUCAAGGAGGACGGCAACAUCCUGGGGCACAAGCUGGAGUACAACUACAACAGCCACAACGUCUAUAUCAUGGCCGACAAGCAGAAGAACGGCAUCAAGGUGAACUUCAAGAUCCGCCACAACAUCGAGGACGGCAGCGUGCAGCUCGCCGACCACUACCAGCAGAACACCCCCAUCGGCGACGGCCCCGUGCUGCUGCCCGACAACCACUACCUGAGCACCCAGUCCGCCCUGAGCAAAGACCCCAACGAGAAGCGCGAUCACAUGGUCCUGCUGGAGUUCGUGACCGCCGCCGGGAUCACUCUCGGCAUGGACGAGCUGUACAAGUAA </p>\n")
    f.write("<br>\n")
    f.write("<p> The reverse complement is: TTACTTGTACAGCTCGTCCATGCCGAGAGTGATCCCGGCGGCGGTCACGAACTCCAGCAGGACCATGTGATCGCGCTTCTCGTTGGGGTCTTTGCTCAGGGCGGACTGGGTGCTCAGGTAGTGGTTGTCGGGCAGCAGCACGGGGCCGTCGCCGATGGGGGTGTTCTGCTGGTAGTGGTCGGCGAGCTGCACGCTGCCGTCCTCGATGTTGTGGCGGATCTTGAAGTTCACCTTGATGCCGTTCTTCTGCTTGTCGGCCATGATATAGACGTTGTGGCTGTTGTAGTTGTACTCCAGCTTGTGCCCCAGGATGTTGCCGTCCTCCTTGAAGTCGATGCCCTTCAGCTCGATGCGGTTCACCAGGGTGTCGCCCTCGAACTTCACCTCGGCGCGGGTCTTGTAGTTGCCGTCGTCCTTGAAGAAGATGGTGCGCTCCTGGACGTAGCCTTCGGGCATGGCGGACTTGAAGAAGTCGTGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGTGGCATCGCCCTCGCCCTCGCCGGACACGCTGAACTTGTGGCCGTTTACGTCGCCGTCCAGCTCGACCAGGATGGGCACCACCCCGGTGAACAGCTCCTCGCCCTTGCTCACCAT </p>\n")
    f.write("<br>\n")
    f.write ("<p> The protein sequence is: MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITLGMDELYK* </p>\n")
    f.write("<br>\n")
    f.write("<p> The Human codon optimized sequence is: ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGCGTGGTGCCCATCCTGGTGGAGCTGGACGGCGACGTGAACGGCCACAAGTTCAGCGTGAGCGGCGAGGGCGAGGGCGACGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTGGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGGTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGAGCGCCATGCCCGAGGGCTACGTGCAGGAGCGGACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGGGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGGATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGCCACAAGCTGGAGTACAACTACAACAGCCACAACGTGTACATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGGCACAACATCGAGGACGGCAGCGTGCAGCTGGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGAGCGCCCTGAGCAAGGACCCCAACGAGAAGCGGGACCACATGGTGCTGCTGGAGTTCGTGACCGCCGCCGGCATCACCCTGGGCATGGACGAGCTGTACAAGTGA </p>\n")
    f.write("<br>\n")
    f.write("<p> The GC content % is: 61.52777777777778 </p>\n")
    f.write("<br>\n")
    f.write("<p> The Tm of the DNA sequence in degrees C is: 2324.5 </p>\n")
    f.write("<br>\n")
    f.write("</body>\n")
    f.write("</html>\n")
    f.close()
writeHTML()
